config/routes.rb
Rails.application.routes.draw do

  scope :module => "etabliocms_actualities" do
    namespace :admin do
      resources :actualities
      resources :categories do
        member do
          put :move
        end
      end
    end
  end

end

app/models/etabliocms_actualities/actuality.rb
module EtabliocmsActualities
  class Actuality < ActiveRecord::Base

    default_scope :order => "updated_at desc"

    scope :recent, lambda { |limit| {:limit => limit, :order => "updated_at desc"} }
    scope :last_edited, lambda { |limit| {:limit => limit, :order => "updated_at desc"} }
    scope :visible, lambda { where(["(publish_date < ? AND unpublish_date > ?) ", Time.now, Time.now]) }
    scope :last_week, lambda { where(['created_at > ? and created_at < ?', 7.days.ago, Time.now]) }

    validates :title, :presence => true
    validates :publish_date, :presence => true
    validates :unpublish_date, :presence => true

    has_slug :to_param => :id_slug
    has_paper_trail

    def summary
      self.perex.present? ? self.perex : self.text
    end

  end
end

app/models/etabliocms_actualities/category.rb
module EtabliocmsActualities
  class Category < ActiveRecord::Base

    has_many :actualities, :dependent => :nullify

    acts_as_nested_set
    attr_accessor :child_of
    after_save :update_position

    validates :title, :presence => true
    validates :locale, :presence => true

    has_slug :to_param => "path"
    has_paper_trail

    def path
      self_and_ancestors.map(&:slug).join("/")
    end

    def other_categories_for_select
      categories = EtabliocmsActualities::Category.order("lft ASC")
      categories = categories.where("id != ?", id) unless new_record?
      categories.map { |d| [d.title, d.id] }
    end

    scope :for_locale, lambda { |locale| where(:locale => locale) }

    private
    def update_position
      if child_of.to_i != parent_id.to_i
        if child_of.present?
          parent = Category.find(child_of)
          move_to_child_of parent unless parent == self or parent == self.parent
          move_to_bottom
        elsif !child_of.nil?
          move_to_root
          move_to_bottom
        end
      end
      self.child_of = nil
    end

  end
end

app/controllers/etabliocms_actualities/admin/actualities_controller.rb
module EtabliocmsActualities
  module Admin
    class ActualitiesController < EtabliocmsCore::Admin::BaseController

      def index
        @actualities = Actuality.order(params[:order] || "created_at DESC").page(params[:page])
      end

      def new
        @actuality = Actuality.new
      end

      def create
        @actuality = Actuality.new(params[:actuality])
        if @actuality.save
          flash[:notice] = t('actuality.created')
          redirect_to :action => 'index'
        else
          render :action => 'new'
        end
      end

      def edit
        @actuality = Actuality.find(params[:id])
      end

      def update
        @actuality = Actuality.find(params[:id])
        if @actuality.update_attributes(params[:actuality])
          flash[:notice] = t('actuality.updated')
          redirect_to :action => 'index'
        else
          render :action => 'edit'
        end
      end

      def destroy
        Actuality.find(params[:id]).destroy
        flash[:notice] = t('actuality.destroyed')
        redirect_to :action => 'index'
      end

    end
  end
end

app/controllers/etabliocms_actualities/admin/categories_controller.rb
module EtabliocmsActualities
  module Admin
    class CategoriesController < EtabliocmsCore::Admin::BaseController

      def new
        @category = Category.new
      end

      def create
        @category = Category.new(params[:category])
        if @category.save
          flash[:notice] = t('category.created')
          redirect_to :action => 'index'
        else
          render :action => 'new'
        end
      end

      def edit
        @category = Category.find(params[:id])
      end

      def update
        @category = Category.find(params[:id])
        if @category.update_attributes(params[:category])
          flash[:notice] = t('category.updated')
          redirect_to :action => 'index'
        else
          render :action => 'edit'
        end
      end

      def destroy
        Category.find(params[:id]).destroy
        flash[:notice] = t('category.destroyed')
        redirect_to :action => 'index'
      end

      def move
        @category = Category.find(params[:id])
        if ["move_lower", "move_higher", "move_to_top", "move_to_bottom"].include?(params[:method])
          @category.send(params[:method])
          flash[:notice] = t('category.moved')
        else
          flash[:notice] = t('category.not_moved')
        end
        redirect_to :action => 'index'
      end

    end
  end
end

app/views/etabliocms_actualities/admin/actualities/_form.html.erb
<fieldset>
  <legend><%= t('actuality.admin_legend') %></legend>

  <%= render "layouts/errors", :target => @actuality %>

  <p>
    <%= f.label :title, :id => "actuality_title_label" %>
    <%= f.text_field :title, :class => 'text-field' %>
  </p>

  <p>
    <%= f.label :perex, :id => "actuality_perex_label" %>
    <%= f.textile_text_area :perex, :class => "small-text-area" %>
  </p>

  <p>
    <%= f.label :text, :id => "actuality_text_label" %>
    <%= f.textile_text_area :text %>
  </p>

  <p>
    <%= f.label :publish_date, :id => "actuality_publish_date_label" %>
    <%= f.datetime_select :publish_date %>
  </p>

  <p>
    <%= f.label :unpublish_date, :id => "actuality_unpublish_date_label" %>
    <%= f.datetime_select :unpublish_date, :default => Time.now + 5.years %>
  </p>

  <p>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, EtabliocmsActualities::Category.all, :id, :title, {:include_blank => true} %>
  </p>

  <p>
    <%= f.label :locale, :id => "category_locale_label" %>
    <%= f.select :locale, I18n.available_locales.map(&:to_s).sort.map { |locale| [I18n.t("admin.locales.#{locale}"), locale.to_s] } %>
  </p>

  <p class="submit-box">
    <%= submit_tag t('admin.save'), :class => 'submit' %>
  </p>

</fieldset>

app/views/etabliocms_actualities/admin/actualities/edit.html.erb
<% set_title_and_breadcrumb t('actuality.edit', :title => @actuality.title) %>

<h1><%= @actuality.title %></h1>

<%= form_for :actuality,  :url => admin_actuality_path(@actuality.id), :html => {:method => :put, :id => "admin-form"} do |f| -%>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end  %>

app/views/etabliocms_actualities/admin/actualities/index.html.erb
<% set_title_and_breadcrumb t('actuality.actualities') %>

<h1><%= t('actuality.actualities') %></h1>

<div class="strap">
  <%= link_to "#{t('actuality.add')} &raquo;".html_safe, new_admin_actuality_path, :class => 'text-icon icon-add' %>
  <%= link_to "#{t('admin.refresh')} &raquo;".html_safe, admin_actualities_path, :class => 'text-icon icon-refresh' %>
  <%= link_to "#{t('admin.back_to_admin')} &raquo;".html_safe, admin_path, :class => 'text-icon icon-backward' %>
</div>

<table class="admin-table">
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.etabliocms_actualities/actuality.title') %> </th>
    <th><%= t('activerecord.attributes.etabliocms_actualities/actuality.publish_date') %></th>
    <th><%= t('activerecord.attributes.etabliocms_actualities/actuality.unpublish_date') %></th>
    <th><%= t('admin.actions') %></th>
  </tr>
  </thead>
  <tbody>

  <% for item in @actualities %>
      <tr class="<%= cycle("odd-row", "even-row") -%>">
        <td><%= link_to item.title, edit_admin_actuality_url(item.id) %></td>
        <td class="center"><%= l item.publish_date, :format => :short %></td>
        <td class="center"><%= l item.unpublish_date, :format => :short %></td>
        <td>
          <%= link_to t('admin.edit'), edit_admin_actuality_url(item.id), :class => 'icon icon-edit', :title => t('admin.edit') %>
          <%= link_to t('admin.destroy'), admin_actuality_url(item.id),
                      :method => :delete,
                      :confirm => t('actuality.destroy_confirmation'),
                      :class => 'icon icon-destroy',
                      :title => t('admin.destroy') %>
        </td>
  <% end %>
  </tbody>
</table>

<%= paginate @actualities %>

app/views/etabliocms_actualities/admin/actualities/new.html.erb
<% set_title_and_breadcrumb t('actuality.new') %>

<h1><%= t('actuality.new') %></h1>

<%= form_for :actuality,  :url => admin_actualities_path, :html => {:method => :post, :id => "admin-form"} do |f| -%>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end  %>

app/views/etabliocms_actualities/admin/categories/_form.html.erb
<%= render "layouts/errors", :target => @category %>

<fieldset>

  <legend><%= t('category.admin_legend') %></legend>

  <p>
    <%= f.label :title, :id => "category_title_label" %>
    <%= f.text_field :title, :class => 'text-field' %>
  </p>

  <p>
    <%= f.label :child_of, :id => "category_child_of_label" %>
    <%= f.select :child_of, [[t('hierarchy.top_level'), nil]] + @category.other_categories_for_select,
                 :selected => @category.parent ? [@category.parent.title, @category.parent_id] : nil %>
  </p>

  <p>
    <%= f.label :locale, :id => "category_locale_label" %>
    <%= f.select :locale, [[t('admin.locales.cs'), 'cs'], [t('admin.locales.en'), 'en'], [t('admin.locales.de'), 'de']] %>
  </p>


  <p>
    <%= f.label :visible, :id => "category_visible_label" %>
    <%= f.boolean_yes_no_select :visible %>
  </p>

  <p>
    <%= f.textile_text_area :text, :width => 560, :height => 200 %>
  </p>

  <% if !@category.new_record? && respond_to?(:category_path) %>
      <p>
        <strong>Náhled: </strong>
        <%= link_to @category.title, category_url(@category, :locale => @category.locale), :"data-popup" => "true" %>
      </p>
  <% end %>

  <p class="submit-box">
    <%= submit_tag t('admin.save'), :class => 'submit' %>
  </p>

</fieldset>

app/views/etabliocms_actualities/admin/categories/edit.html.erb
<% set_title_and_breadcrumb t('category.edit', :title => @category.title) %>

<h1><%= @category.title %></h1>

<%= form_for :category,  :url => admin_category_path(@category.id), :html => {:method => :put, :id => "admin-form"} do |f| -%>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end  %>

app/views/etabliocms_actualities/admin/categories/index.html.erb
<% set_title_and_breadcrumb t('category.categories') %>

<h1><%= t('category.categories') %></h1>

<div class="strap">
  <%= link_to "#{t('category.add')} &raquo;".html_safe, new_admin_category_path, :class => 'text-icon icon-add' %>
  <%= link_to "#{t('admin.refresh')} &raquo;".html_safe, admin_categories_path, :class => 'text-icon icon-refresh' %>
  <%= link_to "#{t('admin.back_to_admin')} &raquo;".html_safe, admin_path, :class => 'text-icon icon-backward' %>
</div>

<table class="admin-table hierarchical-table">
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.etabliocms_actualities/category.title') %></th>
    <th><%= t('admin.created_at') %></th>
    <th><%= t('activerecord.attributes.etabliocms_actualities/category.locale') %></th>
    <th><%= t('admin.actions') %></th>
  </tr>
  </thead>
  <tbody>

  <%= render_table_tree(EtabliocmsActualities::Category.order("lft asc")) %>

  </tbody>
</table>

app/views/etabliocms_actualities/admin/categories/new.html.erb
<% set_title_and_breadcrumb t('category.new') %>

<h1><%= t('category.new') %></h1>

<%= form_for :category,  :url => admin_categories_url, :html => {:method => :post, :id => "admin-form"} do |f| -%>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end  %>

app/views/layouts/_sidebar_actualities.html.erb
<h3><%= image_tag asset_path("admin/sidebar-actualities.png"), :alt => t('actuality.actualities') %><%= t('actuality.actualities') %></h3>
<ul>
  <li><%= link_to_unless_current I18n.t('actuality.actualities_count', :count => EtabliocmsActualities::Actuality.count), admin_actualities_path %></li>
  <li><%= link_to_unless_current t('actuality.add'), new_admin_actuality_path %></li>
  <li><%= link_to_unless_current I18n.t('category.categories_count', :count => EtabliocmsActualities::Category.count), admin_categories_path %></li>
  <li><%= link_to_unless_current t('category.add'), new_admin_category_path %></li>
</ul>